# Options for analysis running
run:
  # Timeout for analysis, e.g. 30s, 5m
  timeout: 5m
  
  # Include test files or not
  tests: true
  
  # Which dirs to skip
  skip-dirs:
    - vendor
    - cmd/client

# Output configuration options
output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate
  format: colored-line-number
  
  # Print lines of code with issue
  print-issued-lines: true

# Linters settings
linters-settings:
  govet:
    # Report about shadowed variables
    check-shadowing: true
  
  golint:
    # Minimal confidence for issues
    min-confidence: 0.8
  
  gocyclo:
    # Minimal code complexity to report
    min-complexity: 15

# Enable or disable specific linters
linters:
  disable-all: true
  enable:
    - errcheck      # Checking for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects unused assignments
    - staticcheck   # Go static analysis
    - typecheck     # Like the front-end of a Go compiler
    - unused        # Checks Go code for unused constants, variables, functions and types
    - gosec        # Inspects source code for security problems
    - gofmt        # Checks if code was gofmt-ed
    - goimports    # Checks import statements
    - misspell     # Finds commonly misspelled English words
    - revive       # Fast, configurable, extensible, flexible, and beautiful linter for Go

# Issues configuration
issues:
  # Maximum count of issues with the same text
  max-same-issues: 3
  
  # Maximum issues count per one linter
  max-issues-per-linter: 50
  
  # Exclude some dirs/files
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
