version: '3'

vars:
  BINARY_NAME: shortener
  BUILD_DIR: build
  MAIN_FILE: cmd/shortener/main.go
  GO_FILES:
    sh: find . -type f -name '*.go'

tasks:
  clean:
    desc: Clean build directory
    cmds:
      - rm -rf {{.BUILD_DIR}}

  dependencies:
    desc: Install dependencies
    cmds:
      - go mod tidy
      - go mod download
      - go mod verify

  build:
    desc: Build the shortener binary
    deps: [clean]
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - |
        export PATH=$PATH:$(go env GOPATH)/bin
        go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_FILE}}
    sources:
      - '**/*.go'
    generates:
      - '{{.BUILD_DIR}}/{{.BINARY_NAME}}'

  lint:
    desc: Run linters
    cmds:
      - |
        export PATH=$PATH:$(go env GOPATH)/bin
        golangci-lint run ./...

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  test_increment_1:
    desc: Test increment 1
    deps: [build]
    cmds:
      - shortenertestbeta -test.v -test.run=^TestIteration1$ -binary-path={{.BUILD_DIR}}/{{.BINARY_NAME}}

  test_increment_2:
    desc: Test increment 2
    deps: [build]
    cmds:
      - shortenertestbeta -test.v -test.run=^TestIteration2$ -source-path=.
  
  test_increment_3:
    desc: Test increment 3
    deps: [build]
    cmds:
      - shortenertestbeta -test.v -test.run=^TestIteration3$ -source-path=.

  test_increment_4:
    desc: Test increment 4
    deps: [build]
    env:
      SERVER_PORT: 8081
    cmds:
      - shortenertestbeta -test.v -test.run=^TestIteration4$ -binary-path={{.BUILD_DIR}}/{{.BINARY_NAME}} -server-port=$SERVER_PORT -source-path=.
  
  test_increment_5:
    desc: Test increment 5
    deps: [build]
    env:
      SERVER_PORT: 9090
    cmds:
      - shortenertestbeta -test.v -test.run=^TestIteration5$ -binary-path={{.BUILD_DIR}}/{{.BINARY_NAME}} -server-port=$SERVER_PORT
  
  test_increment_6:
    desc: Test increment 6
    deps: [build]
    env:
      SERVER_ADDRESS: "localhost:8081"
      BASE_URL: "http://localhost:8081"
      RELEASE_MODE: "release"
      LOG_LEVEL: "info"
    cmds:
      - shortenertestbeta -test.v -test.run=^TestIteration6$ -source-path=.

  test_increment_7:
    desc: Test increment 7
    deps: [build]
    cmds:
      - shortenertestbeta -test.v -test.run=^TestIteration7$ -binary-path={{.BUILD_DIR}}/{{.BINARY_NAME}} -source-path=.

  test_increment_8:
    desc: Test increment 8
    deps: [build]
    cmds:
      - shortenertestbeta -test.v -test.run=^TestIteration8$ -binary-path={{.BUILD_DIR}}/{{.BINARY_NAME}}

  test_increment_all:
    desc: Run all tests
    deps: [
      test_increment_1,
      test_increment_2,
      test_increment_3,
      test_increment_4,
      test_increment_5,
      test_increment_6,
      test_increment_7
    ]
    cmds:
      - echo "All tests passed"

  run:
    desc: Run the shortener binary
    cmds:
      - go run {{.MAIN_FILE}}
